# -*- coding: utf-8 -*-
"""ReginaMaris268855LatLon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1piK2U1l78mTLZiunMmNs36OsBKYW6jRH
"""

import pandas as pd

url = "https://marinetraffic.live/fetchAIS2.php/requests/vesselsonmaptempTTT.php?type=json&seltype=0&selid=244528000"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"}
antwort = requests.get(url, headers = headers)
antwort

df = pd.read_json(url)
df

lat = float(df.iloc[4, 0])
lon = float(df.iloc[5, 0])

from shapely.geometry import Point, Polygon

import pymsteams
myTeamsMessage = pymsteams.connectorcard("https://mdrde.webhook.office.com/webhookb2/60ef16f8-fa87-4c0e-9cc4-c830fe8ac9d3@528d1628-15c0-4deb-ae8d-5a3f37f82b5c/IncomingWebhook/18703ce4f61d41f29dc8810b83fbf3f9/37da9787-3764-49e2-9b44-2338c6b46416")

# Definiere die Eckpunkte des Polygons als Liste von (lon, lat)-Tupeln
polygon_coords_hh = [(9.787445,53.443081), (10.170593,53.443081), (10.170593,53.610433), (9.787445,53.610433)]
polygon_coords_ki = [(10.094376,54.298696), (10.229988,54.298696), (10.229988,54.365158), (10.094376,54.365158)]

# Erstelle ein Polygon-Objekt
polygon_hh = Polygon(polygon_coords_hh)
polygon_ki = Polygon(polygon_coords_ki)

# Definiere die Position als Point-Objekt
position = Point(lon, lat)

# lon und lat sind die Längen- und Breitengrade deiner Position# Überprüfe, ob sich die Position innerhalb des Polygons befindet
if polygon_hh.contains(position):
  message = ("Der Traditionssegler Regina Maris befindet sich in Hamburg.")
elif polygon_ki.contains(position):
  message = ("Der Traditionssegler Regina Maris befindet sich in Kiel.")
else:
  message = ("Der Traditionssegler Regina Maris ist weder in Hamburg noch in Kiel.")

myTeamsMessage.text(message)
myTeamsMessage.send()
